assets:
  - dev.sql.gz
steps:
  - name: Composer install
    command: 'pwd; ls /var/html -al; cd /var/www/html; composer self-update; composer install --prefer-dist'
  - name: Probo CI site setup
    plugin: Drupal
    database: dev.sql.gz
    databaseGzipped: true
    subDirectory: web
    drupalVersion: 8
