assets:
  - dev.sql.gz
steps:
  - name: Composer install
    command: 'cd /src; composer self-update; composer install --prefer-dist'
  - name: Probo CI site setup
    plugin: Drupal
    database: dev.sql.gz
    databaseGzipped: true
    subDirectory: web
    drupalVersion: 8
    settingsAppend: "$config_directories = array(CONFIG_SYNC_DIRECTORY => '../config',);"
  - name: Configuration Import
    command: 'drush cim -y; drush cr;'
